### ISSUE TITLE
support sqLite

### ISSUE THREAD

**Issue by lroal** [alfateam/rdb#10]

**Comment by leocaseiro** [comment]
Does rbd support sqLIte or not yet? Thanks!

**Comment by lroal** [comment]
No I didn't prioritize as there were few requests about it. But I think I should prioritize it now.
Are you using sqlLite only in nodejs or in browser too ?

**Comment by leocaseiro** [comment]
Thanks for your quick respond.
I'm actually using in a browser(safari) with Ionic and Cordova. No Node

**Comment by taoeffect** [comment]
sqlite support for node would be awesome.

Would you consider using [node-sql](https://github.com/brianc/node-sql) to generate the queries? It's a high-quality generic query generator that supports sqlite as well as mysql/postgresql and others.

**Comment by lroal** [comment]
I will most probably use https://www.npmjs.com/package/sqlite3 .
There is very little code that needs to be added, to support sqlite on the serverside.
Thank's for pushing me.

**Comment by lroal** [comment]
I am nearly done with sqlite support now, but serverside only. Streaming is the last piece that is not implemented.

**Comment by lroal** [comment]
I consider supporting sqlite in browser too. But then I need to replace nodejs domain with something like this: [node-continuation-local-storage](https://github.com/othiym23/node-continuation-local-storage) . 
Domain is used for keeping current transaction (persistence ignorance).  
Domain is deprecated in nodejs so I need to replace it anyway.
