### ISSUE TITLE
column mapping value defaults to null/0 , resulting in pkey generation failure

### ISSUE THREAD

**Issue by missShellNose** [alfateam/rdb#15]
I'm trying to get the postgresql generated primary key from Object.id. If I map the id column to Object.id:
```
Object.primaryColumn('id').string().as('id'); //OR
Object.column('id').numeric().as('id'),
```
The id value gets a default value which then is being inserted in the table even if i don't set it in the insert method. Is there a way to get the auto generated id that I'm missing? Please help~ Thank you!

**Comment by lroal** [comment]
Hi!
Auto-generated primary keys are currently not supported. If you are in a position to choose between auto generated and guid (from client side), I definitely recommend guids. It makes things a lot easier and reduces database round trips - and the client can run partly disconnected. However, if you are dealing with a legacy database, you probably don't have that luxury.

Yes, string and numeric have default values null and 0. This is to make things convenient. It is based on the assumption that guid is for PK and numeric is for mathematical. See example on [default values](https://github.com/alfateam/rdb/blob/master/docs/docs.md#_defaultvalues)

If guids are not an option for you, I can change the behaviour as you suggest. But, please consider guids first, and then let me know your decision.

**Comment by lroal** [comment]
By the way, you don't need to map property name if database name is the same. In other words,
this:
```js
Object.primaryColumn('id').string().as('id'); 
Object.column('id').numeric().as('id'),
```
is equivalent to:
```js
Object.primaryColumn('id').string();
Object.column('id').numeric();
```

**Comment by missShellNose** [comment]
Thank you for the response! I'm building a api server with postgresql. Do you use a library to generate sequential guid? or how do you find performance with random guid keys? Thank you!

**Comment by lroal** [comment]
I use https://www.npmjs.com/package/uuid .
You can either use timebased (v1) or random (v4). I use random and haven't had any performance issues. Timebased should be better for performance though.

**Comment by missShellNose** [comment]
ok i will try it out. Thank you!

**Comment by lroal** [comment]
Glad to help. 
Closing the issue for now.
