### ISSUE TITLE
What is the property "lines: true" that I see in almost every example?

### ISSUE THREAD

**Issue by fabiohvp** [alfateam/rdb#51]
Hello, this project seems promising and I was looking through the docs and I saw this property "lines: true" in almost every query, I want to know what is it for?

**Comment by lroal** [comment]
It means you should include the lines relation in the result.

Instead of true, you could also specify which specific columns you want included/excluded.

Btw
You can try out the examples live with the SQLite database on your computer. SQLite db is just a file.

**Comment by lroal** [comment]
if {lines: true} is missing or false, order.lines would be undefined.

Same goes for deliveryAddress and customer.
