### ISSUE TITLE
SurrealDB support 

### ISSUE THREAD

**Issue by CanRau** [alfateam/rdb#59]
Curious on your thoughts on supporting SurrealDB, ideally for surreal.js and surreal.node 🤞

**Comment by lroal** [comment]
That is an interesting database - I haven't heard of it before.
Still, I have decided to put this request on hold for the time being. There are a couple of reasons for this:

**Maturity and Adoption** 
SurrealDB is a relatively new database technology that has yet to see widespread adoption. I prefer to focus our resources on databases that have a larger user base to maximize the impact of the work.  If you have any data or insights regarding its adoption and maturity, I would be very interested to hear them.

**Syntax Compatibility**
SurrealDB uses a specialized SQL syntax that, while simpler, would require a non-trivial amount of work to integrate with our RDB. So I want to make sure it has a large user base, before investing time in it.

I understand the unique benefits SurrealDB offers and I am not ruling out future support. To that end, I am labeling this issue as "on-hold" and closing it for now. I will revisit this suggestion at a later date as the landscape evolves.

**Comment by CanRau** [comment]
Makes sense, thanks for elaborating 🙌
